# Generated by Django 3.2.15 on 2022-09-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
