# Generated by Django 3.2.15 on 2022-09-24 16:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='featured_image'),
        ),
    ]
